{ spark:
  { app_name: "Flight", master: "local[*]" },
  paths: {
    datapath_flight: "../Flight/Inputs/Flights/",
    datapath_weather: "../Flight/Inputs/Weather/",
    datapath_wban: "../Flight/Inputs/wban_airport_timezone.csv",
    output_flight: "../Flight/ParquetFiles/Flight/",
    output_weather: "../Flight/ParquetFiles/Weather/",
    output_csv: "../Flight/Output/",
    output_final_Col_parquet: "../Flight/ParquetFiles/Final_DF_Columns/",
    output_final_line_parquet: "../Flight/ParquetFiles/Final_DF_Lines/"},
  execution: {
    reload_and_train: "BigData" # Possible values : "BigData", "MachineLearning", "All"
  }
}